//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klient", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class Klient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwiskoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie {
            get {
                return this.ImieField;
            }
            set {
                if ((object.ReferenceEquals(this.ImieField, value) != true)) {
                    this.ImieField = value;
                    this.RaisePropertyChanged("Imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko {
            get {
                return this.NazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwiskoField, value) != true)) {
                    this.NazwiskoField = value;
                    this.RaisePropertyChanged("Nazwisko");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Konto", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class Konto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Clear {
            get {
                return this.ClearField;
            }
            set {
                if ((this.ClearField.Equals(value) != true)) {
                    this.ClearField = value;
                    this.RaisePropertyChanged("Clear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pracownik", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class Pracownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Data_zaczeciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StanowiskoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Data_zaczecia {
            get {
                return this.Data_zaczeciaField;
            }
            set {
                if ((this.Data_zaczeciaField.Equals(value) != true)) {
                    this.Data_zaczeciaField = value;
                    this.RaisePropertyChanged("Data_zaczecia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie {
            get {
                return this.ImieField;
            }
            set {
                if ((object.ReferenceEquals(this.ImieField, value) != true)) {
                    this.ImieField = value;
                    this.RaisePropertyChanged("Imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko {
            get {
                return this.NazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwiskoField, value) != true)) {
                    this.NazwiskoField = value;
                    this.RaisePropertyChanged("Nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stanowisko {
            get {
                return this.StanowiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.StanowiskoField, value) != true)) {
                    this.StanowiskoField = value;
                    this.RaisePropertyChanged("Stanowisko");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produkt", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class Produkt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DostepnoscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Dostepnosc {
            get {
                return this.DostepnoscField;
            }
            set {
                if ((this.DostepnoscField.Equals(value) != true)) {
                    this.DostepnoscField = value;
                    this.RaisePropertyChanged("Dostepnosc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="zam_prod", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class zam_prod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ProduktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ZamowieniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IloscField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Produkt {
            get {
                return this.ID_ProduktField;
            }
            set {
                if ((this.ID_ProduktField.Equals(value) != true)) {
                    this.ID_ProduktField = value;
                    this.RaisePropertyChanged("ID_Produkt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Zamowienia {
            get {
                return this.ID_ZamowieniaField;
            }
            set {
                if ((this.ID_ZamowieniaField.Equals(value) != true)) {
                    this.ID_ZamowieniaField = value;
                    this.RaisePropertyChanged("ID_Zamowienia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ilosc {
            get {
                return this.IloscField;
            }
            set {
                if ((this.IloscField.Equals(value) != true)) {
                    this.IloscField = value;
                    this.RaisePropertyChanged("Ilosc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zamowienia", Namespace="http://schemas.datacontract.org/2004/07/DataTemplates.DisplayData")]
    [System.SerializableAttribute()]
    public partial class Zamowienia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Data_zlozeniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_KlientaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Data_zlozenia {
            get {
                return this.Data_zlozeniaField;
            }
            set {
                if ((this.Data_zlozeniaField.Equals(value) != true)) {
                    this.Data_zlozeniaField = value;
                    this.RaisePropertyChanged("Data_zlozenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Klienta {
            get {
                return this.ID_KlientaField;
            }
            set {
                if ((this.ID_KlientaField.Equals(value) != true)) {
                    this.ID_KlientaField = value;
                    this.RaisePropertyChanged("ID_Klienta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAccessService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/Login", ReplyAction="http://tempuri.org/IAccessService/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/Login", ReplyAction="http://tempuri.org/IAccessService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/Register", ReplyAction="http://tempuri.org/IAccessService/RegisterResponse")]
        bool Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/Register", ReplyAction="http://tempuri.org/IAccessService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetKlienty", ReplyAction="http://tempuri.org/IAccessService/GetKlientyResponse")]
        Test.ServiceReference1.Klient[] GetKlienty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetKlienty", ReplyAction="http://tempuri.org/IAccessService/GetKlientyResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Klient[]> GetKlientyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetKonta", ReplyAction="http://tempuri.org/IAccessService/GetKontaResponse")]
        Test.ServiceReference1.Konto[] GetKonta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetKonta", ReplyAction="http://tempuri.org/IAccessService/GetKontaResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Konto[]> GetKontaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetPracownicy", ReplyAction="http://tempuri.org/IAccessService/GetPracownicyResponse")]
        Test.ServiceReference1.Pracownik[] GetPracownicy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetPracownicy", ReplyAction="http://tempuri.org/IAccessService/GetPracownicyResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Pracownik[]> GetPracownicyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetProdkuty", ReplyAction="http://tempuri.org/IAccessService/GetProdkutyResponse")]
        Test.ServiceReference1.Produkt[] GetProdkuty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetProdkuty", ReplyAction="http://tempuri.org/IAccessService/GetProdkutyResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Produkt[]> GetProdkutyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetZam_prody", ReplyAction="http://tempuri.org/IAccessService/GetZam_prodyResponse")]
        Test.ServiceReference1.zam_prod[] GetZam_prody();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetZam_prody", ReplyAction="http://tempuri.org/IAccessService/GetZam_prodyResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.zam_prod[]> GetZam_prodyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetZamowienia", ReplyAction="http://tempuri.org/IAccessService/GetZamowieniaResponse")]
        Test.ServiceReference1.Zamowienia[] GetZamowienia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/GetZamowienia", ReplyAction="http://tempuri.org/IAccessService/GetZamowieniaResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Zamowienia[]> GetZamowieniaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessServiceChannel : Test.ServiceReference1.IAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessServiceClient : System.ServiceModel.ClientBase<Test.ServiceReference1.IAccessService>, Test.ServiceReference1.IAccessService {
        
        public AccessServiceClient() {
        }
        
        public AccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Register(string username, string password) {
            return base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
        
        public Test.ServiceReference1.Klient[] GetKlienty() {
            return base.Channel.GetKlienty();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Klient[]> GetKlientyAsync() {
            return base.Channel.GetKlientyAsync();
        }
        
        public Test.ServiceReference1.Konto[] GetKonta() {
            return base.Channel.GetKonta();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Konto[]> GetKontaAsync() {
            return base.Channel.GetKontaAsync();
        }
        
        public Test.ServiceReference1.Pracownik[] GetPracownicy() {
            return base.Channel.GetPracownicy();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Pracownik[]> GetPracownicyAsync() {
            return base.Channel.GetPracownicyAsync();
        }
        
        public Test.ServiceReference1.Produkt[] GetProdkuty() {
            return base.Channel.GetProdkuty();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Produkt[]> GetProdkutyAsync() {
            return base.Channel.GetProdkutyAsync();
        }
        
        public Test.ServiceReference1.zam_prod[] GetZam_prody() {
            return base.Channel.GetZam_prody();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.zam_prod[]> GetZam_prodyAsync() {
            return base.Channel.GetZam_prodyAsync();
        }
        
        public Test.ServiceReference1.Zamowienia[] GetZamowienia() {
            return base.Channel.GetZamowienia();
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Zamowienia[]> GetZamowieniaAsync() {
            return base.Channel.GetZamowieniaAsync();
        }
    }
}
